/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @gram/functions-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx assetsUploadFunctions.example.ts
 */

import { Gram } from "@gram/functions-sdk";
import { openAsBlob } from "node:fs";

const gram = new Gram();

async function main() {
  const result = await gram.assets.uploadFunctions({
    option1: {
      apikeyHeaderGramKey: process.env["GRAM_APIKEY_HEADER_GRAM_KEY"] ?? "",
      projectSlugHeaderGramProject:
        process.env["GRAM_PROJECT_SLUG_HEADER_GRAM_PROJECT"] ?? "",
    },
  }, {
    contentLength: 858625,
    body: await openAsBlob("example.file"),
  });

  console.log(result);
}

main().catch(console.error);
