/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const Kind = {
  Openapiv3: "openapiv3",
  Image: "image",
  Functions: "functions",
  ChatAttachment: "chat_attachment",
  Unknown: "unknown",
} as const;
export type Kind = OpenEnum<typeof Kind>;

export type Asset = {
  /**
   * The content length of the asset
   */
  contentLength: number;
  /**
   * The content type of the asset
   */
  contentType: string;
  /**
   * The creation date of the asset.
   */
  createdAt: Date;
  /**
   * The ID of the asset
   */
  id: string;
  kind: Kind;
  /**
   * The SHA256 hash of the asset
   */
  sha256: string;
  /**
   * The last update date of the asset.
   */
  updatedAt: Date;
};

/** @internal */
export const Kind$inboundSchema: z.ZodMiniType<Kind, unknown> = openEnums
  .inboundSchema(Kind);

/** @internal */
export const Asset$inboundSchema: z.ZodMiniType<Asset, unknown> = z.pipe(
  z.object({
    content_length: types.number(),
    content_type: types.string(),
    created_at: types.date(),
    id: types.string(),
    kind: Kind$inboundSchema,
    sha256: types.string(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "content_length": "contentLength",
      "content_type": "contentType",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function assetFromJSON(
  jsonString: string,
): SafeParseResult<Asset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Asset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Asset' from JSON`,
  );
}
