/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeploymentFunctions = {
  /**
   * The ID of the uploaded asset.
   */
  assetId: string;
  /**
   * The ID of the deployment asset.
   */
  id: string;
  /**
   * The memory limit in MiB of function runner machines.
   */
  memoryMib?: number | undefined;
  /**
   * The name to give the document as it will be displayed in UIs.
   */
  name: string;
  /**
   * The runtime to use when executing functions.
   */
  runtime: string;
  /**
   * The number of instances to run for the function.
   */
  scale?: number | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  slug: string;
};

/** @internal */
export const DeploymentFunctions$inboundSchema: z.ZodMiniType<
  DeploymentFunctions,
  unknown
> = z.pipe(
  z.object({
    asset_id: types.string(),
    id: types.string(),
    memory_mib: types.optional(types.number()),
    name: types.string(),
    runtime: types.string(),
    scale: types.optional(types.number()),
    slug: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "memory_mib": "memoryMib",
    });
  }),
);

export function deploymentFunctionsFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentFunctions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentFunctions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentFunctions' from JSON`,
  );
}
