/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  OAuthProxyProvider,
  OAuthProxyProvider$inboundSchema,
} from "./o-auth-proxy-provider.js";

export type OAuthProxyServer = {
  /**
   * The audience parameter to send to the upstream OAuth provider
   */
  audience?: string | undefined;
  /**
   * When the OAuth proxy server was created.
   */
  createdAt: Date;
  /**
   * The ID of the OAuth proxy server
   */
  id: string;
  /**
   * The OAuth proxy providers for this server
   */
  oauthProxyProviders?: Array<OAuthProxyProvider> | undefined;
  /**
   * The project ID this OAuth proxy server belongs to
   */
  projectId: string;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  slug: string;
  /**
   * When the OAuth proxy server was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const OAuthProxyServer$inboundSchema: z.ZodMiniType<
  OAuthProxyServer,
  unknown
> = z.pipe(
  z.object({
    audience: types.optional(types.string()),
    created_at: types.date(),
    id: types.string(),
    oauth_proxy_providers: types.optional(
      z.array(OAuthProxyProvider$inboundSchema),
    ),
    project_id: types.string(),
    slug: types.string(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "oauth_proxy_providers": "oauthProxyProviders",
      "project_id": "projectId",
      "updated_at": "updatedAt",
    });
  }),
);

export function oAuthProxyServerFromJSON(
  jsonString: string,
): SafeParseResult<OAuthProxyServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OAuthProxyServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OAuthProxyServer' from JSON`,
  );
}
