/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * The type of OAuth provider
 */
export const ProviderType = {
  Custom: "custom",
  Gram: "gram",
} as const;
/**
 * The type of OAuth provider
 */
export type ProviderType = OpenEnum<typeof ProviderType>;

export type OAuthProxyProvider = {
  /**
   * The authorization endpoint URL
   */
  authorizationEndpoint: string;
  /**
   * When the OAuth proxy provider was created.
   */
  createdAt: Date;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  environmentSlug?: string | undefined;
  /**
   * The grant types supported by this provider
   */
  grantTypesSupported?: Array<string> | undefined;
  /**
   * The ID of the OAuth proxy provider
   */
  id: string;
  /**
   * The type of OAuth provider
   */
  providerType: ProviderType;
  /**
   * The OAuth scopes supported by this provider
   */
  scopesSupported?: Array<string> | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  slug: string;
  /**
   * The token endpoint URL
   */
  tokenEndpoint: string;
  /**
   * The token endpoint auth methods supported by this provider
   */
  tokenEndpointAuthMethodsSupported?: Array<string> | undefined;
  /**
   * When the OAuth proxy provider was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const ProviderType$inboundSchema: z.ZodMiniType<ProviderType, unknown> =
  openEnums.inboundSchema(ProviderType);

/** @internal */
export const OAuthProxyProvider$inboundSchema: z.ZodMiniType<
  OAuthProxyProvider,
  unknown
> = z.pipe(
  z.object({
    authorization_endpoint: types.string(),
    created_at: types.date(),
    environment_slug: types.optional(types.string()),
    grant_types_supported: types.optional(z.array(types.string())),
    id: types.string(),
    provider_type: ProviderType$inboundSchema,
    scopes_supported: types.optional(z.array(types.string())),
    slug: types.string(),
    token_endpoint: types.string(),
    token_endpoint_auth_methods_supported: types.optional(
      z.array(types.string()),
    ),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "authorization_endpoint": "authorizationEndpoint",
      "created_at": "createdAt",
      "environment_slug": "environmentSlug",
      "grant_types_supported": "grantTypesSupported",
      "provider_type": "providerType",
      "scopes_supported": "scopesSupported",
      "token_endpoint": "tokenEndpoint",
      "token_endpoint_auth_methods_supported":
        "tokenEndpointAuthMethodsSupported",
      "updated_at": "updatedAt",
    });
  }),
);

export function oAuthProxyProviderFromJSON(
  jsonString: string,
): SafeParseResult<OAuthProxyProvider, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OAuthProxyProvider$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OAuthProxyProvider' from JSON`,
  );
}
