/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CanonicalToolAttributes,
  CanonicalToolAttributes$inboundSchema,
} from "./canonical-tool-attributes.js";
import {
  ToolAnnotations,
  ToolAnnotations$inboundSchema,
} from "./tool-annotations.js";
import {
  ToolVariation,
  ToolVariation$inboundSchema,
} from "./tool-variation.js";

/**
 * A platform-owned tool served directly by the platform
 */
export type PlatformToolDefinition = {
  /**
   * Tool annotations providing behavioral hints about the tool
   */
  annotations?: ToolAnnotations | undefined;
  /**
   * The original details of a tool
   */
  canonical?: CanonicalToolAttributes | undefined;
  /**
   * The canonical name of the tool. Will be the same as the name if there is no variation.
   */
  canonicalName: string;
  /**
   * Confirmation mode for the tool
   */
  confirm?: string | undefined;
  /**
   * Prompt for the confirmation
   */
  confirmPrompt?: string | undefined;
  /**
   * The creation date of the tool.
   */
  createdAt: Date;
  /**
   * Description of the tool
   */
  description: string;
  /**
   * The ID of the tool
   */
  id: string;
  /**
   * The name of the tool
   */
  name: string;
  /**
   * Optional owning entity ID
   */
  ownerId?: string | undefined;
  /**
   * The entity kind that owns this tool's lifecycle
   */
  ownerKind?: string | undefined;
  /**
   * The ID of the project
   */
  projectId: string;
  /**
   * JSON schema for the request
   */
  schema: string;
  /**
   * Version of the schema
   */
  schemaVersion?: string | undefined;
  /**
   * The backing platform tool source (for example: logs)
   */
  sourceSlug: string;
  /**
   * Summarizer for the tool
   */
  summarizer?: string | undefined;
  /**
   * The URN of this tool
   */
  toolUrn: string;
  /**
   * The last update date of the tool.
   */
  updatedAt: Date;
  variation?: ToolVariation | undefined;
};

/** @internal */
export const PlatformToolDefinition$inboundSchema: z.ZodMiniType<
  PlatformToolDefinition,
  unknown
> = z.pipe(
  z.object({
    annotations: types.optional(ToolAnnotations$inboundSchema),
    canonical: types.optional(CanonicalToolAttributes$inboundSchema),
    canonical_name: types.string(),
    confirm: types.optional(types.string()),
    confirm_prompt: types.optional(types.string()),
    created_at: types.date(),
    description: types.string(),
    id: types.string(),
    name: types.string(),
    owner_id: types.optional(types.string()),
    owner_kind: types.optional(types.string()),
    project_id: types.string(),
    schema: types.string(),
    schema_version: types.optional(types.string()),
    source_slug: types.string(),
    summarizer: types.optional(types.string()),
    tool_urn: types.string(),
    updated_at: types.date(),
    variation: types.optional(ToolVariation$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "canonical_name": "canonicalName",
      "confirm_prompt": "confirmPrompt",
      "created_at": "createdAt",
      "owner_id": "ownerId",
      "owner_kind": "ownerKind",
      "project_id": "projectId",
      "schema_version": "schemaVersion",
      "source_slug": "sourceSlug",
      "tool_urn": "toolUrn",
      "updated_at": "updatedAt",
    });
  }),
);

export function platformToolDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<PlatformToolDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformToolDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformToolDefinition' from JSON`,
  );
}
