/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  FunctionResourceDefinition,
  FunctionResourceDefinition$inboundSchema,
} from "./function-resource-definition.js";

/**
 * A polymorphic resource - currently only function resources are supported
 */
export type Resource = {
  /**
   * A function resource
   */
  functionResourceDefinition?: FunctionResourceDefinition | undefined;
};

/** @internal */
export const Resource$inboundSchema: z.ZodMiniType<Resource, unknown> = z.pipe(
  z.object({
    function_resource_definition: types.optional(
      FunctionResourceDefinition$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "function_resource_definition": "functionResourceDefinition",
    });
  }),
);

export function resourceFromJSON(
  jsonString: string,
): SafeParseResult<Resource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Resource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Resource' from JSON`,
  );
}
