/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const Type = {
  Function: "function",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type ResourceEntry = {
  /**
   * The ID of the resource
   */
  id: string;
  /**
   * The name of the resource
   */
  name: string;
  /**
   * The URN of the resource
   */
  resourceUrn: string;
  type: Type;
  /**
   * The uri of the resource
   */
  uri: string;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);

/** @internal */
export const ResourceEntry$inboundSchema: z.ZodMiniType<
  ResourceEntry,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    resource_urn: types.string(),
    type: Type$inboundSchema,
    uri: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "resource_urn": "resourceUrn",
    });
  }),
);

export function resourceEntryFromJSON(
  jsonString: string,
): SafeParseResult<ResourceEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResourceEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResourceEntry' from JSON`,
  );
}
