/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ToolVariation = {
  /**
   * The confirmation mode for the tool variation
   */
  confirm?: string | undefined;
  /**
   * The confirmation prompt for the tool variation
   */
  confirmPrompt?: string | undefined;
  /**
   * The creation date of the tool variation
   */
  createdAt: string;
  /**
   * The description of the tool variation
   */
  description?: string | undefined;
  /**
   * Override: if true, the tool may perform destructive updates
   */
  destructiveHint?: boolean | undefined;
  /**
   * The ID of the tool variation group
   */
  groupId: string;
  /**
   * The ID of the tool variation
   */
  id: string;
  /**
   * Override: if true, repeated calls have no additional effect
   */
  idempotentHint?: boolean | undefined;
  /**
   * The name of the tool variation
   */
  name?: string | undefined;
  /**
   * Override: if true, the tool interacts with external entities
   */
  openWorldHint?: boolean | undefined;
  /**
   * Override: if true, the tool does not modify its environment
   */
  readOnlyHint?: boolean | undefined;
  /**
   * The name of the source tool
   */
  srcToolName: string;
  /**
   * The URN of the source tool
   */
  srcToolUrn: string;
  /**
   * The summarizer of the tool variation
   */
  summarizer?: string | undefined;
  /**
   * Display name override for the tool
   */
  title?: string | undefined;
  /**
   * The last update date of the tool variation
   */
  updatedAt: string;
};

/** @internal */
export const ToolVariation$inboundSchema: z.ZodMiniType<
  ToolVariation,
  unknown
> = z.pipe(
  z.object({
    confirm: types.optional(types.string()),
    confirm_prompt: types.optional(types.string()),
    created_at: types.string(),
    description: types.optional(types.string()),
    destructive_hint: types.optional(types.boolean()),
    group_id: types.string(),
    id: types.string(),
    idempotent_hint: types.optional(types.boolean()),
    name: types.optional(types.string()),
    open_world_hint: types.optional(types.boolean()),
    read_only_hint: types.optional(types.boolean()),
    src_tool_name: types.string(),
    src_tool_urn: types.string(),
    summarizer: types.optional(types.string()),
    title: types.optional(types.string()),
    updated_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "confirm_prompt": "confirmPrompt",
      "created_at": "createdAt",
      "destructive_hint": "destructiveHint",
      "group_id": "groupId",
      "idempotent_hint": "idempotentHint",
      "open_world_hint": "openWorldHint",
      "read_only_hint": "readOnlyHint",
      "src_tool_name": "srcToolName",
      "src_tool_urn": "srcToolUrn",
      "updated_at": "updatedAt",
    });
  }),
);

export function toolVariationFromJSON(
  jsonString: string,
): SafeParseResult<ToolVariation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolVariation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolVariation' from JSON`,
  );
}
