/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ExternalMCPHeaderDefinition,
  ExternalMCPHeaderDefinition$inboundSchema,
} from "./external-mcp-header-definition.js";
import {
  ExternalOAuthServer,
  ExternalOAuthServer$inboundSchema,
} from "./external-o-auth-server.js";
import {
  FunctionEnvironmentVariable,
  FunctionEnvironmentVariable$inboundSchema,
} from "./function-environment-variable.js";
import {
  OAuthEnablementMetadata,
  OAuthEnablementMetadata$inboundSchema,
} from "./o-auth-enablement-metadata.js";
import {
  OAuthProxyServer,
  OAuthProxyServer$inboundSchema,
} from "./o-auth-proxy-server.js";
import {
  PromptTemplate,
  PromptTemplate$inboundSchema,
} from "./prompt-template.js";
import { Resource, Resource$inboundSchema } from "./resource.js";
import {
  SecurityVariable,
  SecurityVariable$inboundSchema,
} from "./security-variable.js";
import {
  ServerVariable,
  ServerVariable$inboundSchema,
} from "./server-variable.js";
import { Tool, Tool$inboundSchema } from "./tool.js";
import {
  ToolsetOrigin,
  ToolsetOrigin$inboundSchema,
} from "./toolset-origin.js";

export type Toolset = {
  /**
   * The account type of the organization
   */
  accountType: string;
  /**
   * When the toolset was created.
   */
  createdAt: Date;
  /**
   * The ID of the custom domain to use for the toolset
   */
  customDomainId?: string | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  defaultEnvironmentSlug?: string | undefined;
  /**
   * Description of the toolset
   */
  description?: string | undefined;
  /**
   * The external MCP header definitions that are relevant to the toolset
   */
  externalMcpHeaderDefinitions?: Array<ExternalMCPHeaderDefinition> | undefined;
  externalOauthServer?: ExternalOAuthServer | undefined;
  /**
   * The function environment variables that are relevant to the toolset
   */
  functionEnvironmentVariables?: Array<FunctionEnvironmentVariable> | undefined;
  /**
   * The ID of the toolset
   */
  id: string;
  /**
   * Whether the toolset is enabled for MCP
   */
  mcpEnabled?: boolean | undefined;
  /**
   * Whether the toolset is public in MCP
   */
  mcpIsPublic?: boolean | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  mcpSlug?: string | undefined;
  /**
   * The name of the toolset
   */
  name: string;
  oauthEnablementMetadata: OAuthEnablementMetadata;
  oauthProxyServer?: OAuthProxyServer | undefined;
  /**
   * The organization ID this toolset belongs to
   */
  organizationId: string;
  origin?: ToolsetOrigin | undefined;
  /**
   * The project ID this toolset belongs to
   */
  projectId: string;
  /**
   * The prompt templates in this toolset -- Note: these are actual prompts, as in MCP prompts
   */
  promptTemplates: Array<PromptTemplate>;
  /**
   * The resource URNs in this toolset
   */
  resourceUrns: Array<string>;
  /**
   * The resources in this toolset
   */
  resources: Array<Resource>;
  /**
   * The security variables that are relevant to the toolset
   */
  securityVariables?: Array<SecurityVariable> | undefined;
  /**
   * The server variables that are relevant to the toolset
   */
  serverVariables?: Array<ServerVariable> | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  slug: string;
  /**
   * The mode to use for tool selection
   */
  toolSelectionMode: string;
  /**
   * The tool URNs in this toolset
   */
  toolUrns: Array<string>;
  /**
   * The tools in this toolset
   */
  tools: Array<Tool>;
  /**
   * The version of the toolset (will be 0 if none exists)
   */
  toolsetVersion: number;
  /**
   * When the toolset was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const Toolset$inboundSchema: z.ZodMiniType<Toolset, unknown> = z.pipe(
  z.object({
    account_type: types.string(),
    created_at: types.date(),
    custom_domain_id: types.optional(types.string()),
    default_environment_slug: types.optional(types.string()),
    description: types.optional(types.string()),
    external_mcp_header_definitions: types.optional(
      z.array(ExternalMCPHeaderDefinition$inboundSchema),
    ),
    external_oauth_server: types.optional(ExternalOAuthServer$inboundSchema),
    function_environment_variables: types.optional(
      z.array(FunctionEnvironmentVariable$inboundSchema),
    ),
    id: types.string(),
    mcp_enabled: types.optional(types.boolean()),
    mcp_is_public: types.optional(types.boolean()),
    mcp_slug: types.optional(types.string()),
    name: types.string(),
    oauth_enablement_metadata: OAuthEnablementMetadata$inboundSchema,
    oauth_proxy_server: types.optional(OAuthProxyServer$inboundSchema),
    organization_id: types.string(),
    origin: types.optional(ToolsetOrigin$inboundSchema),
    project_id: types.string(),
    prompt_templates: z.array(PromptTemplate$inboundSchema),
    resource_urns: z.array(types.string()),
    resources: z.array(Resource$inboundSchema),
    security_variables: types.optional(z.array(SecurityVariable$inboundSchema)),
    server_variables: types.optional(z.array(ServerVariable$inboundSchema)),
    slug: types.string(),
    tool_selection_mode: types.string(),
    tool_urns: z.array(types.string()),
    tools: z.array(Tool$inboundSchema),
    toolset_version: types.number(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "account_type": "accountType",
      "created_at": "createdAt",
      "custom_domain_id": "customDomainId",
      "default_environment_slug": "defaultEnvironmentSlug",
      "external_mcp_header_definitions": "externalMcpHeaderDefinitions",
      "external_oauth_server": "externalOauthServer",
      "function_environment_variables": "functionEnvironmentVariables",
      "mcp_enabled": "mcpEnabled",
      "mcp_is_public": "mcpIsPublic",
      "mcp_slug": "mcpSlug",
      "oauth_enablement_metadata": "oauthEnablementMetadata",
      "oauth_proxy_server": "oauthProxyServer",
      "organization_id": "organizationId",
      "project_id": "projectId",
      "prompt_templates": "promptTemplates",
      "resource_urns": "resourceUrns",
      "security_variables": "securityVariables",
      "server_variables": "serverVariables",
      "tool_selection_mode": "toolSelectionMode",
      "tool_urns": "toolUrns",
      "toolset_version": "toolsetVersion",
      "updated_at": "updatedAt",
    });
  }),
);

export function toolsetFromJSON(
  jsonString: string,
): SafeParseResult<Toolset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Toolset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Toolset' from JSON`,
  );
}
