/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ExternalMCPHeaderDefinition,
  ExternalMCPHeaderDefinition$inboundSchema,
} from "./external-mcp-header-definition.js";
import {
  FunctionEnvironmentVariable,
  FunctionEnvironmentVariable$inboundSchema,
} from "./function-environment-variable.js";
import {
  PromptTemplateEntry,
  PromptTemplateEntry$inboundSchema,
} from "./prompt-template-entry.js";
import {
  ResourceEntry,
  ResourceEntry$inboundSchema,
} from "./resource-entry.js";
import {
  SecurityVariable,
  SecurityVariable$inboundSchema,
} from "./security-variable.js";
import {
  ServerVariable,
  ServerVariable$inboundSchema,
} from "./server-variable.js";
import { ToolEntry, ToolEntry$inboundSchema } from "./tool-entry.js";
import {
  ToolsetOrigin,
  ToolsetOrigin$inboundSchema,
} from "./toolset-origin.js";

export type ToolsetEntry = {
  /**
   * When the toolset was created.
   */
  createdAt: Date;
  /**
   * The ID of the custom domain to use for the toolset
   */
  customDomainId?: string | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  defaultEnvironmentSlug?: string | undefined;
  /**
   * Description of the toolset
   */
  description?: string | undefined;
  /**
   * The external MCP header definitions that are relevant to the toolset
   */
  externalMcpHeaderDefinitions?: Array<ExternalMCPHeaderDefinition> | undefined;
  /**
   * The function environment variables that are relevant to the toolset
   */
  functionEnvironmentVariables?: Array<FunctionEnvironmentVariable> | undefined;
  /**
   * The ID of the toolset
   */
  id: string;
  /**
   * Whether the toolset is enabled for MCP
   */
  mcpEnabled?: boolean | undefined;
  /**
   * Whether the toolset is public in MCP
   */
  mcpIsPublic?: boolean | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  mcpSlug?: string | undefined;
  /**
   * The name of the toolset
   */
  name: string;
  /**
   * The organization ID this toolset belongs to
   */
  organizationId: string;
  origin?: ToolsetOrigin | undefined;
  /**
   * The project ID this toolset belongs to
   */
  projectId: string;
  /**
   * The prompt templates in this toolset -- Note: these are actual prompts, as in MCP prompts
   */
  promptTemplates: Array<PromptTemplateEntry>;
  /**
   * The resource URNs in this toolset
   */
  resourceUrns: Array<string>;
  /**
   * The resources in this toolset
   */
  resources: Array<ResourceEntry>;
  /**
   * The security variables that are relevant to the toolset
   */
  securityVariables?: Array<SecurityVariable> | undefined;
  /**
   * The server variables that are relevant to the toolset
   */
  serverVariables?: Array<ServerVariable> | undefined;
  /**
   * A short url-friendly label that uniquely identifies a resource.
   */
  slug: string;
  /**
   * The mode to use for tool selection
   */
  toolSelectionMode: string;
  /**
   * The tool URNs in this toolset
   */
  toolUrns: Array<string>;
  /**
   * The tools in this toolset
   */
  tools: Array<ToolEntry>;
  /**
   * When the toolset was last updated.
   */
  updatedAt: Date;
};

/** @internal */
export const ToolsetEntry$inboundSchema: z.ZodMiniType<ToolsetEntry, unknown> =
  z.pipe(
    z.object({
      created_at: types.date(),
      custom_domain_id: types.optional(types.string()),
      default_environment_slug: types.optional(types.string()),
      description: types.optional(types.string()),
      external_mcp_header_definitions: types.optional(
        z.array(ExternalMCPHeaderDefinition$inboundSchema),
      ),
      function_environment_variables: types.optional(
        z.array(FunctionEnvironmentVariable$inboundSchema),
      ),
      id: types.string(),
      mcp_enabled: types.optional(types.boolean()),
      mcp_is_public: types.optional(types.boolean()),
      mcp_slug: types.optional(types.string()),
      name: types.string(),
      organization_id: types.string(),
      origin: types.optional(ToolsetOrigin$inboundSchema),
      project_id: types.string(),
      prompt_templates: z.array(PromptTemplateEntry$inboundSchema),
      resource_urns: z.array(types.string()),
      resources: z.array(ResourceEntry$inboundSchema),
      security_variables: types.optional(
        z.array(SecurityVariable$inboundSchema),
      ),
      server_variables: types.optional(z.array(ServerVariable$inboundSchema)),
      slug: types.string(),
      tool_selection_mode: types.string(),
      tool_urns: z.array(types.string()),
      tools: z.array(ToolEntry$inboundSchema),
      updated_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "custom_domain_id": "customDomainId",
        "default_environment_slug": "defaultEnvironmentSlug",
        "external_mcp_header_definitions": "externalMcpHeaderDefinitions",
        "function_environment_variables": "functionEnvironmentVariables",
        "mcp_enabled": "mcpEnabled",
        "mcp_is_public": "mcpIsPublic",
        "mcp_slug": "mcpSlug",
        "organization_id": "organizationId",
        "project_id": "projectId",
        "prompt_templates": "promptTemplates",
        "resource_urns": "resourceUrns",
        "security_variables": "securityVariables",
        "server_variables": "serverVariables",
        "tool_selection_mode": "toolSelectionMode",
        "tool_urns": "toolUrns",
        "updated_at": "updatedAt",
      });
    }),
  );

export function toolsetEntryFromJSON(
  jsonString: string,
): SafeParseResult<ToolsetEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolsetEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolsetEntry' from JSON`,
  );
}
