/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assetsUploadFunctions } from "../funcs/assets-upload-functions.js";
import { assetsUploadOpenAPIv3 } from "../funcs/assets-upload-open-ap-iv3.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Assets extends ClientSDK {
  /**
   * uploadFunctions assets
   *
   * @remarks
   * Upload functions to Gram.
   */
  async uploadFunctions(
    security: operations.UploadFunctionsSecurity,
    request: operations.UploadFunctionsRequest,
    options?: RequestOptions,
  ): Promise<components.UploadFunctionsResult> {
    return unwrapAsync(assetsUploadFunctions(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * uploadOpenAPIv3 assets
   *
   * @remarks
   * Upload an OpenAPI v3 document to Gram.
   */
  async uploadOpenAPIv3(
    security: operations.UploadOpenAPIv3AssetSecurity,
    request: operations.UploadOpenAPIv3AssetRequest,
    options?: RequestOptions,
  ): Promise<components.UploadOpenAPIv3Result> {
    return unwrapAsync(assetsUploadOpenAPIv3(
      this,
      security,
      request,
      options,
    ));
  }
}
