/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsActive } from "../funcs/deployments-active.js";
import { deploymentsCreate } from "../funcs/deployments-create.js";
import { deploymentsEvolveDeployment } from "../funcs/deployments-evolve-deployment.js";
import { deploymentsGetById } from "../funcs/deployments-get-by-id.js";
import { deploymentsLatest } from "../funcs/deployments-latest.js";
import { deploymentsRedeployDeployment } from "../funcs/deployments-redeploy-deployment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Deployments extends ClientSDK {
  /**
   * getActiveDeployment deployments
   *
   * @remarks
   * Get the active deployment for a project.
   */
  async active(
    security: operations.GetActiveDeploymentSecurity,
    request?: operations.GetActiveDeploymentRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.GetActiveDeploymentResult> {
    return unwrapAsync(deploymentsActive(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * createDeployment deployments
   *
   * @remarks
   * Create a deployment to load tool definitions.
   */
  async create(
    security: operations.CreateDeploymentSecurity,
    request: operations.CreateDeploymentRequest,
    options?: RequestOptions,
  ): Promise<components.CreateDeploymentResult> {
    return unwrapAsync(deploymentsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * evolve deployments
   *
   * @remarks
   * Create a new deployment with additional or updated tool sources.
   */
  async evolveDeployment(
    security: operations.EvolveDeploymentSecurity,
    request: operations.EvolveDeploymentRequest,
    options?: RequestOptions,
  ): Promise<components.EvolveResult> {
    return unwrapAsync(deploymentsEvolveDeployment(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * getDeployment deployments
   *
   * @remarks
   * Get a deployment by its ID.
   */
  async getById(
    security: operations.GetDeploymentSecurity,
    request: operations.GetDeploymentRequest,
    options?: RequestOptions,
  ): Promise<components.GetDeploymentResult> {
    return unwrapAsync(deploymentsGetById(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * getLatestDeployment deployments
   *
   * @remarks
   * Get the latest deployment for a project.
   */
  async latest(
    security: operations.GetLatestDeploymentSecurity,
    request?: operations.GetLatestDeploymentRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.GetLatestDeploymentResult> {
    return unwrapAsync(deploymentsLatest(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * redeploy deployments
   *
   * @remarks
   * Redeploys an existing deployment.
   */
  async redeployDeployment(
    security: operations.RedeployDeploymentSecurity,
    request: operations.RedeployDeploymentRequest,
    options?: RequestOptions,
  ): Promise<components.RedeployResult> {
    return unwrapAsync(deploymentsRedeployDeployment(
      this,
      security,
      request,
      options,
    ));
  }
}
