/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { keysValidate } from "../funcs/keys-validate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Keys extends ClientSDK {
  /**
   * verifyKey keys
   *
   * @remarks
   * Verify an api key
   */
  async validate(
    security: operations.ValidateAPIKeySecurity,
    request?: operations.ValidateAPIKeyRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.ValidateKeyResult> {
    return unwrapAsync(keysValidate(
      this,
      security,
      request,
      options,
    ));
  }
}
