/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Assets } from "./assets.js";
import { Deployments } from "./deployments.js";
import { Keys } from "./keys.js";
import { Toolsets } from "./toolsets.js";

export class Gram extends ClientSDK {
  private _assets?: Assets;
  get assets(): Assets {
    return (this._assets ??= new Assets(this._options));
  }

  private _deployments?: Deployments;
  get deployments(): Deployments {
    return (this._deployments ??= new Deployments(this._options));
  }

  private _keys?: Keys;
  get keys(): Keys {
    return (this._keys ??= new Keys(this._options));
  }

  private _toolsets?: Toolsets;
  get toolsets(): Toolsets {
    return (this._toolsets ??= new Toolsets(this._options));
  }
}
