/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetsGetBySlug } from "../funcs/toolsets-get-by-slug.js";
import { toolsetsList } from "../funcs/toolsets-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Toolsets extends ClientSDK {
  /**
   * getToolset toolsets
   *
   * @remarks
   * Get detailed information about a toolset including full HTTP tool definitions
   */
  async getBySlug(
    security: operations.GetToolsetSecurity,
    request: operations.GetToolsetRequest,
    options?: RequestOptions,
  ): Promise<components.Toolset> {
    return unwrapAsync(toolsetsGetBySlug(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * listToolsets toolsets
   *
   * @remarks
   * List all toolsets for a project
   */
  async list(
    security: operations.ListToolsetsSecurity,
    request?: operations.ListToolsetsRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.ListToolsetsResult> {
    return unwrapAsync(toolsetsList(
      this,
      security,
      request,
      options,
    ));
  }
}
